######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 20 02:28:43 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += helloworld.cpp
