#!/usr/bin/perl

print "Content-type: text/html\n\n";
print "<html><head>\n";
print "<title>CGI Test</title>\n";
print "</head>\n";
print "<body><h2>I just wrote a Web page using Perl!</h2>\n";
print "</body></html>\n";
